"""
=============================================================================
UPI Fraud Detection System - Database Models (models.py)
=============================================================================
SQLAlchemy ORM Data Schema for:
- User (Role-Based Authentication: USER / ADMIN)
- Transaction (UPI Telemetry and Behavioral Factors)
- Prediction (Risk Scores, Fraud Probability & Resolution Action)
- ModelMetrics (Trained Algorithm Benchmark History)
=============================================================================
"""

from datetime import datetime, timezone
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()

class User(db.Model):
    """
    User entity supporting role-based access control (USER / ADMIN).
    Uses secure bcrypt/pbkdf2 hashing (via werkzeug.security).
    """
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False, index=True)
    password_hash = db.Column(db.String(255), nullable=False)
    role = db.Column(db.String(20), nullable=False, default='USER')  # 'USER' or 'ADMIN'
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    transactions = db.relationship('Transaction', backref='user', lazy=True, cascade="all, delete-orphan")

    def set_password(self, password: str):
        """Hashes raw password securely."""
        self.password_hash = generate_password_hash(password)

    def check_password(self, password: str) -> bool:
        """Verifies supplied password against stored hash."""
        return check_password_hash(self.password_hash, password)

    def is_admin(self) -> bool:
        """Checks if user has administrative rights."""
        return self.role.upper() == 'ADMIN'

    def to_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'email': self.email,
            'role': self.role,
            'created_at': self.created_at.strftime('%Y-%m-%d %H:%M:%S') if self.created_at else None
        }


class Transaction(db.Model):
    """
    Stores individual UPI transaction requests with behavioral context.
    """
    __tablename__ = 'transactions'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'), nullable=True, index=True)
    amount = db.Column(db.Float, nullable=False)
    time = db.Column(db.Integer, nullable=False)  # Hour 0 - 23
    transaction_type = db.Column(db.String(50), nullable=False, default='Other')
    transaction_frequency = db.Column(db.Integer, nullable=False, default=1)
    avg_transaction_amount = db.Column(db.Float, nullable=False, default=1500.0)
    is_new_beneficiary = db.Column(db.Integer, nullable=False, default=0)  # 0 or 1
    device_changed = db.Column(db.Integer, nullable=False, default=0)      # 0 or 1
    location_changed = db.Column(db.Integer, nullable=False, default=0)    # 0 or 1
    failed_attempts = db.Column(db.Integer, nullable=False, default=0)
    beneficiary_frequency = db.Column(db.Integer, nullable=False, default=1)
    high_tx_reason = db.Column(db.String(255), nullable=True)
    upi_id = db.Column(db.String(100), nullable=True)
    payment_mode = db.Column(db.String(50), nullable=True, default='UPI ID / VPA')
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    # One-to-one relationship with Prediction
    prediction = db.relationship('Prediction', backref='transaction', uselist=False, cascade="all, delete-orphan")

    def to_dict(self):
        return {
            'id': self.id,
            'user_id': self.user_id,
            'amount': self.amount,
            'time': self.time,
            'transaction_type': self.transaction_type,
            'high_tx_reason': self.high_tx_reason,
            'upi_id': self.upi_id,
            'payment_mode': self.payment_mode,
            'transaction_frequency': self.transaction_frequency,
            'avg_transaction_amount': self.avg_transaction_amount,
            'is_new_beneficiary': bool(self.is_new_beneficiary),
            'device_changed': bool(self.device_changed),
            'location_changed': bool(self.location_changed),
            'failed_attempts': self.failed_attempts,
            'beneficiary_frequency': self.beneficiary_frequency,
            'created_at': self.created_at.strftime('%Y-%m-%d %H:%M:%S') if self.created_at else None
        }


class Prediction(db.Model):
    """
    Stores risk assessment output generated by the machine learning pipeline.
    """
    __tablename__ = 'predictions'

    id = db.Column(db.Integer, primary_key=True)
    transaction_id = db.Column(db.Integer, db.ForeignKey('transactions.id', ondelete='CASCADE'), nullable=False, index=True)
    fraud_probability = db.Column(db.Float, nullable=False)
    risk_score = db.Column(db.Integer, nullable=False)  # 0 to 100
    risk_level = db.Column(db.String(20), nullable=False)  # 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
    status = db.Column(db.String(30), nullable=False)  # 'SAFE', 'SUSPICIOUS', 'FRAUD LIKELY'
    action_status = db.Column(db.String(20), nullable=False, default='PENDING')  # 'PENDING', 'VERIFIED', 'CANCELLED'
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def to_dict(self):
        return {
            'id': self.id,
            'transaction_id': self.transaction_id,
            'fraud_probability': self.fraud_probability,
            'risk_score': self.risk_score,
            'risk_level': self.risk_level,
            'status': self.status,
            'action_status': self.action_status,
            'created_at': self.created_at.strftime('%Y-%m-%d %H:%M:%S') if self.created_at else None
        }


class ModelMetrics(db.Model):
    """
    Benchmark scores for compared classification algorithms.
    """
    __tablename__ = 'model_metrics'

    id = db.Column(db.Integer, primary_key=True)
    model_name = db.Column(db.String(100), nullable=False)
    accuracy = db.Column(db.Float, nullable=False)
    precision = db.Column(db.Float, nullable=False)
    recall = db.Column(db.Float, nullable=False)
    f1_score = db.Column(db.Float, nullable=False)
    roc_auc = db.Column(db.Float, nullable=False)
    pr_auc = db.Column(db.Float, nullable=True)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def to_dict(self):
        return {
            'id': self.id,
            'model_name': self.model_name,
            'accuracy': round(self.accuracy, 2),
            'precision': round(self.precision, 2),
            'recall': round(self.recall, 2),
            'f1_score': round(self.f1_score, 2),
            'roc_auc': round(self.roc_auc, 2),
            'pr_auc': round(self.pr_auc, 2) if self.pr_auc is not None else None,
            'created_at': self.created_at.strftime('%Y-%m-%d %H:%M:%S') if self.created_at else None
        }
